### ISSUE TITLE
motd banner: weird display in Ubuntu

### ISSUE THREAD

**Issue by ashledombos** [OpenMandrivaAssociation/bash#10]
Hi,
Here is how it's displayed in Ubuntu 16.04 LTS (yeah I know, have to use it at my work).

![selection_030](https://user-images.githubusercontent.com/513335/26876718-bfb383d4-4b87-11e7-821d-97efc27f0257.png)

While it should be this
![image](https://user-images.githubusercontent.com/513335/26876818-232d3a0e-4b88-11e7-98fa-f9566f43adba.png)

**Comment by fedya** [comment]
Yes, it's gnome terminal issue with colors.
you need to enable full colors support for gnome-terminal (check your
settings)

2017-06-07 14:53 GMT+03:00 ashledombos <notifications@github.com>:
